### PR TITLE
Maven release 2.9.2

### PR DESCRIPTION
**Pull request by JockX**

### CODE REVIEW

**Comment by JockX** [comment]
This PR contains two commits: 1 setting revision suitable for releasing in Maven Central (Sets correct artifact version), and the second one bumps the version to next snapshot. They should not be squashed togheter.

The artifacts build on Corretto JDK11/Windows 10 at 75e02a3 are submitted to sonatype staging, and are one click away from being released to maven central - at least I know the setup is right. They are however signed by by own PGP key (mateusz.pietryga@jockx.net), therefore I believe it would be way better if the regular team member redid the upload with pgp matching their email address.

The command to do the semi-manual upload without the pom.xml edits is:
```
git checkout 75e02a3 
mvn clean install -Ppackage gpg:sign org.sonatype.plugins:nexus-staging-maven-plugin:deploy -DserverId=ossrh -DnexusUrl=https://oss.sonatype.org/
```

Just make sure settings.xml does contains the servers entry:
```
    <server>
        <id>ossrh</id>
        <username>sonatype-username</username>
        <password>sonatype-password</password>
    </server>  
```

**Comment by JockX** [comment]
Resolves #23

**Comment by tresf** [comment]
@JockX thanks kindly.

I've added the Maven publishing hints to our [Publishing-a-Release](https://github.com/java-native/jssc/wiki/Publishing-a-Release) documentation on our wiki.

Note, with other projects I don't normally hard-code version information into `README.md` like you have since it goes into the source-tree and is more places to maintain.  Since this seems to be a fairly common Maven convention, I'm leaving it for now.

I'm committing these however the native libraries will still be versioned for 2.9.1 (which is correct and accurate) assuming you didn't attempt to bundle the update `.dll` into the artifact.  If you did, it could cause regressions as explained in #9 and may require a subsequent release to revert.

In regards to the PGP email address, it would either be yours or mine, so I'm not worried about that specifically.  At time of writing this, the project doesn't have a dedicated email.  If you'd like me to register one prior to publishing, let me know, I'd be happy to do so.

**Comment by tresf** [comment]
Also, once published, the releases area should be updated to reflect the new binary to be consistent with GitHub release convention.

https://github.com/java-native/jssc/releases

**Comment by tresf** [comment]
GitHub required a rebase for whatever reason, so the commit ids will change slightly from your post above.

```diff
- git checkout 75e02a3 
+ git checkout 27f75cd
mvn clean install -Ppackage gpg:sign org.sonatype.plugins:nexus-staging-maven-plugin:deploy -DserverId=ossrh -DnexusUrl=https://oss.sonatype.org/
```

**Pull request merged**
