### PR TITLE
WIP: Pass the bytes along with the SerialPortEventa

### LINKED ISSUE #87: Passing port listener to port is clunky and errorprone
Currently, to add an event listener to a port you have to do:
```Java
port.addEventListener(new MyPortListener(port));
```
where you add the listener to the port and pass the same port to the new MyPortListener class.

Instead I propose the SerialPortEvent gets passed the bytes in the buffer as the event fires.

Closed by #86

### PR DESCRIPTION
**Pull request by Omnieboer**
SerialPortEvent now also saves the byte buffer. It does introduce the SerialPortException to a function that didn't have it before. I'm not sure how this should be handled, thus this is WIP.

Reason for passing along the bytes:
https://github.com/java-native/jssc/issues/85#issuecomment-829255470
And from Slack (me):
> So, I'm not sure I understand the code correctly, but I don't think it's great to call `port.addEventListener(MyPortListener(port))` , the port given to the listener could be a different port than the port the listener is being assigned to. I'm currently working on a PR to have the bytes that trigger a `SerialPortEvent` given along with the event, so then in your own `PortListener`, you can do something like `event.getBytes()` to return a byte array of the latest message.

This makes the example implementation of the event listener in Java the following:
```Java
public static void main(String[] args) throws SerialPortException {
        SerialPort port = new SerialPort("COM10");
        port.openPort();
        port.setParams(BAUDRATE_9600, DATABITS_8, STOPBITS_1, PARITY_NONE);
        // port.setParams(9600, 8, 1, 0); // alternate technique
        int mask = SerialPort.MASK_RXCHAR + SerialPort.MASK_CTS + SerialPort.MASK_DSR;
        port.setEventsMask(mask);
        port.addEventListener(new MyPortListener() /* defined below */);
}

class MyPortListener implements SerialPortEventListener {
    public void serialEvent(SerialPortEvent event) {
        if (event.isRXCHAR()) { // data is available
            // read data, if 10 bytes available
            if (event.getEventValue() == 10) {
                byte[] buffer = event.getBytes();
                System.out.println(Arrays.toString(buffer));
            }
        } else if (event.isCTS()) { // CTS line has changed state
            if (event.getEventValue() == 1) { // line is ON
                System.out.println("CTS - ON");
            } else {
                System.out.println("CTS - OFF");
            }
        } else if (event.isDSR()) { // DSR line has changed state
            if (event.getEventValue() == 1) { // line is ON
                System.out.println("DSR - ON");
            } else {
                System.out.println("DSR - OFF");
            }
        }
    }
}
```

This code works for me, tested with 0,01 second interval between messages of 10 bytes.

Closes #87

### CODE REVIEW

**Comment by tresf** [comment]
I'm wondering if better encapsulation would actually be to have `SerialPortEventListener` a nested class within `SerialPort` so that it has direct access to it's own `SerialPort.this` instance.  If so, we should retain the old namespace as deprecated (even as an extension to the nested class) as to not break backwards compatibility.

This would only fix encapsulation though, not necessarily make it less clunky, I'll explain... 

My experience with eventLIsteners is mostly limited to Swing and AWT, **neither which stash references to the objects that require them**.  For that reason, I find this statement from #87 to be a bit misleading:

> passing port listener to port is clunky

Passing callee by reference isn't much different than, say, a JButton.  In the case of AWT/Swing events, there's a way to get the caller, so that might be the closest we'd have.

I think what is perceived as "clunky" from an OO perspective is that internally, `SerialPortEvent`  has reference to the `portName` (String), not `SerialPort` (Object).

https://github.com/java-native/jssc/blob/28de0f5daf754ca4dd5fee45bc426fed374979f9/src/main/java/jssc/SerialPortEvent.java#L33

However, I believe this design decision was intended by scr3mer to keep the CPP mapping back to Java as simple as possible.  If a pointer to the parent object is attainable, I think we should prefer that, since ports and listeners are nearly always a 1:1 relationship.

> errorprone

I see no evidence of the API being errorprone in its current state.  On the contrary, swallowing exceptions blindly seems to be error prone. 🍻 I realize you've commented "What do we do?" but I think the user should be able to handle the exceptions themselves, which can range from the port being closed, to a timeout occurringg (`SerialPortException`, `SerialPortTimeoutException`)

For example, `readBytes()` checks to see if the port is open and also provides an optional timeout value.    We shouldn't assume people don't want this functionality simply because a listener is attached.

https://github.com/java-native/jssc/blob/a9f1f1b4203303d3e934f3d2a5910260a3e22344/src/main/java/jssc/SerialPort.java#L584-L588

Lastly, and this is very important, a PR shouldn't ever break the API unless absolutely necessary without first deprecating it for a long while, it's just common courtesy. 🍻 

Last, some implementations decided to [only `readBytes()` when the `isRXCHAR()` is `true`](https://github.com/qzind/tray/blob/802d1f8f2d47b7c36d9f6c1187a117d0170f6567/src/qz/communication/SerialIO.java#L74-L212), I think this use-case may still be desired, no?

**Comment by tresf** [comment]
Sorry for the delay...

I took a longer look and came up with the following workable example that uses a lambda, doesn't need to keep track of the port.  I think this is very close to what you're aiming for, but without removing the functionality of the `readBytes(...)`.

```java
 port.addEventListener(event -> {
    if(event.isRXCHAR()){ // data is available
        // read data, if 10 bytes available
        if(event.getEventValue() == 10){
            try {
                byte[] buffer = port.readBytes(10);
            } catch (SerialPortException ex) {
                System.out.println(ex);
            }
        }
    }
    // ... 
}); 
```

To do this, you'll need to apply a diff something like this: https://gist.github.com/tresf/96ed6ce0cf37c4f227f01b342ff5ace9

I haven't tested this code yet, but what it does is attempt to preserve the existing class signatures for backwards compatibility while maintaining a reference to the `SerialPort` that triggered the event to begin with.

This should work because although a listener can listen upon multiple ports, the events will have the `SerialPort` object referenced, allowing `readBytes(...)` without retaining (or passing in) a special pointer.

**Comment by Omnieboer** [comment]
The following now indeed works, thanks for the idea @tresf 
I tested this quickly with messages with 0,01 sec delay between them.

I'll mark this PR ready for review.

```Java
class MyPortListener implements SerialPortEventListener {
    public void serialEvent(SerialPortEvent event) {
        if (event.isRXCHAR()) { // data is available
            // read data, if 10 bytes available
            if (event.getEventValue() == 10) {
                try {
                    byte[] buffer = event.getPort().readBytes();
                    System.out.println(Arrays.toString(buffer));
                } catch (SerialPortException ex) {
                    System.out.println(ex);
                }
            }
        } else if (event.isCTS()) { // CTS line has changed state
            if (event.getEventValue() == 1) { // line is ON
                System.out.println("CTS - ON");
            } else {
                System.out.println("CTS - OFF");
            }
        } else if (event.isDSR()) { // DSR line has changed state
            if (event.getEventValue() == 1) { // line is ON
                System.out.println("DSR - ON");
            } else {
                System.out.println("DSR - OFF");
            }
        }
    }
}
```

**Comment by tresf** [comment]
Thanks.  I think this is safe to merge.  We can update the examples once the next release is finished.

**Pull request merged**
