### PR TITLE
Add RISC-V support

### PR DESCRIPTION
**Pull request by pietrygamat**

### CODE REVIEW

**Comment by pietrygamat** [comment]
@tresf do you have readlily available RISC-V hardware?
Command
```
docker run -it --rm --workdir=/work -v $(pwd):/work docker.io/dockcross/linux-riscv64 bash -c mvn clean install -P dockcross -Dos.target.name=linux -Dos.target.arch=riscv64 -Dos.target.bitness=64
```
does produce _something_ .

**Comment by tresf** [comment]
Thanks, I was preparing the same.  Let's also add `riscv32` while we're at it.

> @tresf do you have readily available RISC-V hardware?

Not yet, but I do have a Qemu instance, which will at least let us know if the initial JNI portions are working.

**Comment by tresf** [comment]
Test build (with https://github.com/scijava/native-lib-loader/pull/48):

[jssc-2.9.6-SNAPSHOT.jar.zip](https://github.com/java-native/jssc/files/13275848/jssc-2.9.6-SNAPSHOT.jar.zip)

**Comment by tresf** [comment]
Qemu testing for RISCV64 is passing.  I'm able to list the virtual COM port, open it and send data.

**Comment by tresf** [comment]
`native-lib-loader` has been updated to 2.5.0 with `riscv32|64` support per https://github.com/scijava/native-lib-loader/pull/48#issuecomment-1799543994

**Comment by tresf** [comment]
@pietrygamat I think this is ready for merge.  Any objections?

**Comment by pietrygamat** [comment]
> @pietrygamat I think this is ready for merge. Any objections?

It looks good to me.

**Pull request merged**
